// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"github.com/google/wire"
	"shortly/pkg/service"
)

// Injectors from container.go:

func NewContext() service.ShortenService {
	shortenService := service.NewShortenService()
	return shortenService
}

// container.go:

var InjectorSet = wire.NewSet(service.NewShortenService)
